### ISSUE TITLE
This plugin breaks Hot Reloading

### ISSUE THREAD

**Issue by jim-moody** [andrew-codes/gatsby-plugin-elasticlunr-search#1]
Not sure why exactly, but I think it might be because we are calling `createNode` inside of `onCreateNode` which might be an infinite loop type situation?

**Comment by andrew-codes** [comment]
@jim-moody Thanks for finding and filling the issue. Your hypothesis was correct; it should only append to the search index and re-create the node for supported node types as defined in the `gatsby-config.js` file.

I have published a new patch for the fix. Let me know if you find any additional issues. Thanks again!
