### ISSUE TITLE
This plugin needs a working example or demo

### ISSUE THREAD

**Issue by GoChartingAdmin** [andrew-codes/gatsby-plugin-elasticlunr-search#5]

**Comment by andrew-codes** [comment]
I think that is a great idea! I will spin up a repo sometime this week to start creating a basic example. I would love to get any feedback or help; both in terms of 👀 and code.

Thanks again for submitting this issue!

**Comment by andrew-codes** [comment]
Link to repo to house demo site: https://github.com/andrew-codes/gatsby-plugin-elasticlunr-search-demo

**Comment by GoChartingAdmin** [comment]
Looking forward to it.  I am personally interested to see its implementation on the gatsby example with Contentful.  Thank you

https://github.com/gatsbyjs/gatsby/tree/master/examples/using-contentful

**Comment by moonmeister** [comment]
I'm struggling to understand how to implement this as well. Would love a demo. Happy to help build it if I can understand how to implement the search box. Thanks!

**Comment by andrew-codes** [comment]
I am going to take some time this upcoming weekend to put together a demo repo. It would be helpful in debugging #6 as well.

@moonmeister We could remote pair program on the creation of the demo site if you would like. That would not only help and put my feet to the fire, but get you going on your own site.

**Comment by moonmeister** [comment]
@andrew-codes Happy to help, I should have time Saturday or Sunday.

**Comment by andrew-codes** [comment]
Awesome! What time zone are you in? I'm across the country from my home until the 24th. I will have limited availability this weekend, but will make time to pair on this. We'll just need to coordinate a time. How flexible are you on Sat. and Sunday and when do you have time slots then? I'll follow up with what my schedule will be as soon as I find it out. Thanks! :-)

**Comment by moonmeister** [comment]
I'm on the west coast (PST). Pretty much any time, Sunday before 1 is the only slot I know I'll be busy. Let me know what works best for you.

**Comment by moonmeister** [comment]
@andrew-codes any idea when/if you'll have time?

**Comment by andrew-codes** [comment]
@moonmeister I apologize for the late notice, but it appears like I won't have the time I originally thought I would have. I have a little time to work on it, but not in a place where I can pair unfortunatley. There is already a repo, though empty, for this can be found here: https://github.com/andrew-codes/gatsby-plugin-elasticlunr-search-demo

I'm going to do the most basic setup and make some issues with the little time I do have. If you would like to take one of the issues and open a PR that would be super helpful. Thanks!

**Comment by andrew-codes** [comment]
@moonmeister, I posted a repo with a working demo: https://github.com/andrew-codes/gatsby-plugin-elasticlunr-search-demo but it could use some love; specifically in the read me. Would you be willing to take a crack at it? If not, I'll take a look later today or tomorrow.

cc: @GoChartingAdmin

**Comment by moonmeister** [comment]
@andrew-codes I messed around with it and it seems to kinda work. I'm probably just missing something. I tried then to implement it on my own demo site and I never got it working. I got it to index data finally and to show up on a page. But, as soon as I tried to do a search it started throwing errors. 

<img width="610" alt="screen shot 2018-01-23 at 8 23 33 pm" src="https://user-images.githubusercontent.com/2730871/35314482-5aed0a02-007b-11e8-8111-ae2cf8ed6adc.png">

also react was throwing a fit

<img width="979" alt="screen shot 2018-01-23 at 8 22 54 pm" src="https://user-images.githubusercontent.com/2730871/35314486-644cb28c-007b-11e8-9e3d-fe5c86728109.png">


Not sure what's up with react. I'm guessing the search issue because `props` comes from the sidebar nav you have that I don't. but that's another component and I'm placing `Search` directly into a page. I may be not understanding something, but it seems that needs to be wrapped into the search component. Make it totally self contained with no dependencies on external components.

Thanks!

**Comment by andrew-codes** [comment]
@moonmeister I wouldn't be surprised if there was an issue, I didn't have much time to put it together. I'll take a look at this later this afternoon when I have some more free time. Thanks! :-)

**Comment by andrew-codes** [comment]
@moonmeister The bottom error may indicate that you are importing a module with different casings in different places. Something like `import React from 'react';` and then somewhere else `import React from 'React';`. I *think* that is what is causing the error; though I cannot tell which module is imported in this way based on the message alone. My guess on which module would be it being React.

Is the first error message from running the demo site or from your own search component? Do you have a link to yours or post a snippet of it and I will take a look.

Also, fwiw, the demo repo does have at least one bug: when you search and get no results, it shows all results. It only will filter the nav bar links when there is at least one match. I plan on filing an issue and working on that soon. Hope that helps.

**Comment by andrew-codes** [comment]
I think I resolved the showing all results instead of no results btw. https://github.com/andrew-codes/gatsby-plugin-elasticlunr-search-demo/issues/1

**Comment by andrew-codes** [comment]
I'm going to go ahead and close this issue. There is now a [demo site](https://gatbsy-plugin-search.andrew.codes) and [repo](https://github.com/andrew-codes/gatsby-plugin-elasticlunr-search-demo) that illustrates using the plugin.
