### ISSUE TITLE
Warnings about multiple equal name modules due to upper and lower case react.

### ISSUE THREAD

**Issue by faylor** [andrew-codes/gatsby-plugin-elasticlunr-search#8]
For Example on Windows getting alot of these: 
 
warning  in ./~/react/lib/KeyEscapeUtils.js

There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

 warning  in ./~/React/lib/KeyEscapeUtils.js

There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

Mine resolved by changing the component example use lowercase 'react' instead of the proposed 'React': 
FROM: import React, {Component} from 'React';
TO: import React, {Component} from 'react';
...
Kind of obvious but just in-case it confused someone else... (I have no idea about react so might be incredibly stupid of me!)

**Comment by andrew-codes** [comment]
Oh, good catch! Thanks for submitting something. Have you checked out the demo site for a more in-depth example by chance? https://github.com/andrew-codes/gatsby-plugin-elasticlunr-search-demo and the demo site of the demo: http://gatsby-plugin-search.andrew.codes/

**Comment by andrew-codes** [comment]
Just resolved this issue, so closing it. Thanks again!
